pub const SNAKE_NODE_SIZE: f32 = 36.0;
pub const EASY_MODE_FIXED_TIMESTEP: f64 = 1.0;
pub const NORMAL_MODE_FIXED_TIMESTEP: f64 = 0.6;
pub const HARD_MODE_FIXED_TIMESTEP: f64 = 0.3;

pub const BOUNDARY_WIDTH: f32 = 17. * SNAKE_NODE_SIZE;
pub const BOUNDARY_HEIGHT: f32 = 17. * SNAKE_NODE_SIZE;

pub const WINDOW_WIDTH: f32 = 1100.;
pub const WINDOW_HEIGHT: f32 = 800.;